### ISSUE TITLE
Looks great!

### ISSUE THREAD

**Issue by soggybag** [TkRain23/mygithubpage#1]
I really like your web site, great work. Here are a few suggestion. 

The card images of your projects on the home page is great. The text at right angle is hard to read. The format is good and interesting, the text should be left to right. It's too hard to read as it is. 

The bio paragraph could use a little line-height. Try `line-height:1.5` as a starting point. 

Think about closing up the space between the Page title and the bio paragraph. Might look better if there was the same amount of space above the bio as there is below the title. This will give you room to add some line-height...

I like the icons at the bottom of the page. They seem to be a little too far apart. Put them together. Put these together in the center so they feel like a related group of options.

**Comment by timkaing** [comment]
Thanks for the feedback! I've gone ahead fixed up those issues. 

In regard to the cards, I wanted to give a vertical card look, despite my assets being horizontal. 
I then created the hover effect to display the name of the project legibly while also redirecting the user to it's respective source.
