### ISSUE TITLE
Whoa, breaking the rules!

### ISSUE THREAD

**Issue by soggybag** [TkRain23/mygithubpage#2]
https://github.com/TkRain23/Personal-Website/blob/9b1afb63987baffe486c62c1c0561abdc151a18c/index.html#L10

You aren't supposed to be using any libraries. You should be writing all of the CSS yourself! 

Use Bootstrap for other projects but here I'd like you to learn to CSS without Bootstrap to get a better understanding of CSS. Remove these and do write the styles yourself. You can do it!

**Comment by timkaing** [comment]
Hey Mitchell! I believe I linked a separate personal page in the tracker. This was one I built 4 years ago as a freshmen in college.

Please see this repo instead and sorry for the inconvenience: https://github.com/TkRain23/FEW-1.1-Personal-Page
